// utils/menuData.js

export const menuItems = [
  {
    id: '1',
    name: 'Almuerzo completo',
    description: 'Plato fuerte + bebida + postre',
    price: 8.50,
    badges: ['Más vendido'],
    image: '/plates/almuerzo.jpg',
  },
  {
    id: '2',
    name: 'Sánduche especial',
    description: 'Pan artesanal, jamón, queso, vegetales',
    price: 6.00,
    badges: ['Propio', 'Picante'],
    image: '/plates/sanduche.jpg',
  },
  {
    id: '3',
    name: 'Ensalada César',
    description: 'Lechuga, pollo, croutons y aderezo César',
    price: 7.00,
    badges: ['Vegetariano'],
    image: '/plates/ensalada.jpg',
  },
  {
    id: '4',
    name: 'Pizza Clásica',
    description: 'Tomate, queso mozzarella y albahaca fresca',
    price: 9.00,
    badges: ['Más vendido'],
    image: '/plates/pizza.jpg',
  },
  {
    id: '5',
    name: 'Hamburguesa Gourmet',
    description: 'Carne Angus, queso cheddar, bacon y cebolla caramelizada',
    price: 10.50,
    badges: ['Propio'],
    image: '/plates/hamburguesa.jpg',
  },
  {
    id: '6',
    name: 'Lomo saltado',
    description: 'Trozos de lomo con cebolla, tomate y papas fritas',
    price: 11.00,
    badges: ['Picante'],
    image: '/plates/lomo.jpg',
  },
  {
    id: '7',
    name: 'Ceviche de camarón',
    description: 'Camarón, limón, cebolla morada y cilantro',
    price: 12.00,
    badges: ['Fresco'],
    image: '/plates/ceviche.jpg',
  },
  {
    id: '8',
    name: 'Chaufa de pollo',
    description: 'Arroz frito estilo chino con trozos de pollo',
    price: 8.00,
    badges: ['Propio'],
    image: '/plates/chaufa.jpg',
  },
  {
    id: '9',
    name: 'Tacos mexicanos',
    description: 'Tortillas con carne, salsa, cilantro y cebolla',
    price: 7.50,
    badges: ['Picante'],
    image: '/plates/tacos.jpg',
  },
  {
    id: '10',
    name: 'Postre del día',
    description: 'Delicioso postre casero, varía diariamente',
    price: 4.00,
    badges: ['Dulce'],
    image: '/plates/postre.jpg',
  },
];
